[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
# nine_dragons = "Aq2uX5QSx6twi3Yua19fhcNkzV2XYMim9HoztQso8r2N"
nine_dragons = "BMm21yWi9vMxTnxFPUtweNdW53wXbRktBPGbcwyq4CxX"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "Localnet"
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[cluster.devnet]
url = "https://devnet.helius-rpc.com/?api-key=975e42bc-9bb2-4aa3-9fd5-7a8a10719df6"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
